### ISSUE TITLE
Allow objects without declared fields

### ISSUE THREAD

**Issue by bsouthga** [tyranid-org/tyranid#10]
I had a property `notes` on a `User` collection like so...

``` javascript
var User = Tyr.Collection({
  id: 'u00',
  name: 'user',
  dbName: 'users',
  fields: {
    _id:                     { is:   'mongoid' },
    email:                   { is:   'email', required : true },
    notes:                   { is:   'object' },
  }
});
```

If I then run `User.fromClient({email : 'test@test.com', notes: {'u00234234234' : 'test'}})` I will get an error here : https://github.com/tyranid-org/tyranid/blob/6dee6a716d067310767512ae86eb7e4a24b97e80/tyranid.js#L1478

This is currently fixable by adding a fields declaration like so `{ is:   'object', fields : [] }`.

**Comment by dimensia** [comment]
Not sure when this was fixed, but it's working now.  Added test case.
