### ISSUE TITLE
Server validation for subscriptions

### ISSUE THREAD

**Issue by yangchristian** [tyranid-org/tyranid#108]
Right now, there's no way to validate a client subscription with application logic.

For instance, say you have a collection like this:
```ts
const Notification = new Tyr.Collection({
  fields: {
    recipientId: { link: 'user', required: true },
  ...
```
An application level server endpoint could implement its own checks, such as making sure the current user is the recipient. On the client you could technically bypass those checks:
```ts
// On client
Tyr.byName.notification.subscribe({
  recipientId: randomUserId
});
```

Solution might just be to use something like [tyranid-gracl](https://github.com/tyranid-org/tyranid-gracl) for this use case. However, that won't address use case of completely custom application logic.

Do subscriptions trigger other events? Perhaps we could implement an application-level `pre-find` handler?

**Comment by dimensia** [comment]
Documentation around how to do this is at:

http://tyranid.org/#validatingSubscriptions
