### ISSUE TITLE
Dependency inject socket.io and have Collection.subscribe() if not present

### ISSUE THREAD

**Issue by yangchristian** [tyranid-org/tyranid#118]
Right now, Tyranid defines `Collection.subscribe()` at runtime, which means we have an implicit dependency on socket.io and that application code calling `Collection.subscribe()` will error when socket.io isn't present.

Ideas:
- Pass in socket.io as a param to Tyranid config/bootstrap (i.e. dependency inject it). This eliminates any implicit dependencies.
- Always have `Collection.subscribe()`  defined and just have it noop if we don't have a valid passed-in socket.io. This lets us not have to write many application level checks around each call to `Collection.subscribe()`.

**Comment by bsouthga** [comment]
just a note, I think @blaqbern is currently blocked on this for storybook -- though I think we could probably put the stuff behind the storybook flag for now (I'm also happy to do a quick pr).
