### ISSUE TITLE
tyr.config throws error if no collection named "user" is defined by third party code

### ISSUE THREAD

**Issue by bsouthga** [tyranid-org/tyranid#63]
currently, the [definition of the log collection requires that a "user" collection be defined](https://github.com/tyranid-org/tyranid/blob/d8d43701e7e90f5ebf15b9bcc281adf7330c6fec/src/log/log.js#L83) but does not provide a default one if none is given by the user.

Maybe `Log` should only have a user field if it is explicitly passed by config? Otherwise, you must define a `user` collection.

**Comment by dimensia** [comment]
This should be fixed by http://tyranid.org/blog#0.2.52
