### ISSUE TITLE
Add $toClient/toClient() post function for filtering

### ISSUE THREAD

**Issue by shindig** [tyranid-org/tyranid#84]
I have a use case where a document has a collection of objects, and I would like $toClient() to filter which objects in that collection are returned in the client document, perhaps through a `post` transformation function, defined in the model on either the collection itself or on the property.  

In my case, I would need to filter the contents based on who is requesting the document, and would use Tyr.local.user to determine what is returned.

**Comment by dimensia** [comment]
Added, you can now register a toClient/fromClient function on the model as a lifecycle hook.
